export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export EDITOR="nvim"
export VISUAL="$EDITOR"
export OS="$(uname -s)"
export PATH="$HOME/.local/bin:$PATH"

# Use my custom agent socket for mac
if [[ "$OSTYPE" == darwin* ]]; then
    export SSH_AUTH_SOCK="$HOME/.ssh/agent/openssh.sock"
fi
