assert_lefthook_installed = true

[[pre-commit.jobs]]
name = "deadnix"
glob = "*.nix"
run = "deadnix --fail {staged_files}"

[[pre-commit.jobs]]
name = "nil"
glob = "*.nix"
run = "nil diagnostics --deny-warnings {staged_files}"

[[pre-commit.jobs]]
interactive = true
name = "treefmt"
run = "treefmt --config-file .config/treefmt.toml {staged_files}"
stage_fixed = true

[[pre-commit.jobs]]
name = "statix"
glob = "*.nix"
run = "for file in {staged_files}; do statix check -c .config/statix.toml --format errfmt \"$file\" || exit 1; done"

[[pre-commit.jobs]]
name = "typos"
run = "typos -c .config/typos.toml {staged_files}"

[[pre-commit.jobs]]
name = "selene"
glob = "*.lua"
run = "selene --config .config/selene.toml {staged_files}"
