[bar]
order = ["default"]

[bar.default]
background_opacity = 0.5
center = ["clock", "notifications"]
end = ["tray", "bluetooth", "volume", "brightness", "session"]
font_family = "Consolas"
font_weight = 700
margin_edge = 0
margin_ends = 0
radius = 0
shadow = false
thickness = 22

[nightlight]
enabled = true

[osd]
position = "top_right"

[shell]
external_ip_enabled = true
polkit_agent = true
telemetry_enabled = false

[shell.screenshot]
directory = "/tmp"
show_cursor = true

[theme]
builtin = "Ayu"
mode = "dark"
source = "builtin"

[wallpaper]
directory = "/home/michael/Pictures/wallpapers"

[weather]
unit = "imperial"

[widget.launcher]
glyph = "rocket"

[widget.notifications]
hide_when_no_unread = true
