# My customized pure prompt
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$nix_shell\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$battery\
$jobs\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[.](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []

[nix_shell]
format = "$state"
impure_msg = "[✱ ](yellow)"
pure_msg = "[✱ ](green)"
unknown_msg = "[✱ ](red)"
